CFLAGS+=$(shell luvit --cflags)
LDFLAGS+=$(shell luvit --libs)

all: luv.luvit

SOURCE_FILES=\
	src/dns.c \
	src/fs.c \
	src/handle.c \
	src/luv.c \
	src/luv.h \
	src/misc.c \
	src/pipe.c \
	src/process.c \
	src/stream.c \
	src/tcp.c \
	src/timer.c \
	src/tty.c \
	src/util.c

luv.luvit: ${SOURCE_FILES} src/luv.h
	$(CC) -c src/luv.c ${CFLAGS} -o luv.o
	$(CC) luv.o ${LDFLAGS} -o $@
	rm luv.o

clean:
	rm -f luv.luvit
