CFLAGS=$(shell luvit --cflags)
LIBS=$(shell luvit --libs)

all: luv.luvit

common.o: src/common.c src/common.h
	$(CC) -c $< -o $@ ${CFLAGS}

luv.o: src/luv.c src/luv.h src/luv_functions.c
	$(CC) -c $< -o $@ ${CFLAGS}

luv.luvit: luv.o common.o
	$(CC) $^ -o $@ ${SHARED_LIB_FLAGS} ${LIBS}

clean:
	rm -f luv.luvit *.o
