require('lib/tap')(function (test)

  test("simple prepare", function (print, p, expect, uv)
    local prepare = uv.new_prepare()
    uv.prepare_start(prepare, expect(function (self)
      assert(self == prepare)
      p("prepare", prepare)
      uv.prepare_stop(prepare)
      uv.close(prepare, expect(function (self)
        assert(self == prepare)
      end))
    end))
  end)

  test("simple check", function (print, p, expect, uv)
    local check = uv.new_check()
    uv.check_start(check, expect(function (self)
      assert(self == check)
      p("check", check)
      uv.check_stop(check)
      uv.close(check, expect(function (self)
        assert(self == check)
      end))
    end))

    -- Trigger with a timer
    local timer = uv.new_timer()
    uv.timer_start(timer, expect(function()
      p("timeout", timer)
      uv.timer_stop(timer)
      uv.close(timer)
    end), 10, 0)
  end)

  test("simple idle", function (print, p, expect, uv)
    local idle = uv.new_idle()
    uv.idle_start(idle, expect(function (self)
      assert(self == idle)
      p("idle", idle)
      uv.idle_stop(idle)
      uv.close(idle, expect(function (self)
        assert(self == idle)
      end))
    end))
  end)

end)
