return require('lib/tap')(function (test)
  --thread not return anything
  test("test thread sleep msecs in loop thread", function(print,p,expect,uv)
    local sleep = 1000
    local b = os.time()
    uv.sleep(sleep)
    local e = os.time()
    local cost = (e-b)
    p("stdout", {sleep=string.format('sleep %d ms',1000),string.format('cost %d seconds',cost)})
    assert(cost>=sleep/1000,"should equals")
  end)

  test("test thread create", function(print,p,expect,uv)
    local sleep = 1000
    local thread_id = uv.new_thread()
    local b = os.time()
    uv.thread_create(thread_id,function(sleep,...) 
      local uv = require('luv')
      uv.sleep(sleep)
    end,sleep)
    uv.thread_join(thread_id)
    local e = os.time()
    print(e,b)
    local cost = (e-b)
    p("stdout", {sleep=string.format('sleep %d ms',1000),string.format('cost %d seconds',cost)})
    assert(cost>=sleep/1000,"should equals")
  end)

  test("test thread create with arguments", function(print,p,expect,uv)
    local thread_id = uv.new_thread()
    local b = os.clock()
    uv.thread_create(thread_id,function(num,s,null,bool,five,hw) 
      assert(type(num)=="number")
      assert(type(s)=="string")
      assert(null==nil)
      assert(bool==false)
      assert(five==5)
      assert(hw=='helloworld')
    end, 500, 'string', nil, false, 5, "helloworld")
    uv.thread_join(thread_id)
  end)

end)
