require('lib/tap')(function (test)
  test("basic", function (print, p, expect, uv)
    local server = uv.new_tcp()
    uv.tcp_bind(server, "::", 0)
    uv.listen(server, 128, expect(function (self, err)
      p("server on connection", self)
      assert(self == server)
      assert(not err)
      uv.shutdown(server)
      uv.close(server)
    end))

    local address = uv.tcp_getsockname(server)
    p{server=server,address=address}

    local client = uv.new_tcp()
    local req = uv.tcp_connect(client, "::1", address.port, expect(function (self, err)
      p("client on connect", self, err)
      assert(self == client)
      assert(not err)
      uv.shutdown(client, expect(function (self, err)
        p("client on shutdown", self, err)
        assert(self == client)
        assert(not err)
        uv.close(client)
      end))
    end))
    p{client=client,req=req}
  end)
end)
